// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/dog.proto

package dog

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindSmartDogMessage struct {
	DogId                string   `protobuf:"bytes,1,opt,name=dogId,proto3" json:"dogId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindSmartDogMessage) Reset()         { *m = FindSmartDogMessage{} }
func (m *FindSmartDogMessage) String() string { return proto.CompactTextString(m) }
func (*FindSmartDogMessage) ProtoMessage()    {}
func (*FindSmartDogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e9f8fd0872a655, []int{0}
}

func (m *FindSmartDogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindSmartDogMessage.Unmarshal(m, b)
}
func (m *FindSmartDogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindSmartDogMessage.Marshal(b, m, deterministic)
}
func (m *FindSmartDogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindSmartDogMessage.Merge(m, src)
}
func (m *FindSmartDogMessage) XXX_Size() int {
	return xxx_messageInfo_FindSmartDogMessage.Size(m)
}
func (m *FindSmartDogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FindSmartDogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FindSmartDogMessage proto.InternalMessageInfo

func (m *FindSmartDogMessage) GetDogId() string {
	if m != nil {
		return m.DogId
	}
	return ""
}

type FindSmartDogResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindSmartDogResponse) Reset()         { *m = FindSmartDogResponse{} }
func (m *FindSmartDogResponse) String() string { return proto.CompactTextString(m) }
func (*FindSmartDogResponse) ProtoMessage()    {}
func (*FindSmartDogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e9f8fd0872a655, []int{1}
}

func (m *FindSmartDogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindSmartDogResponse.Unmarshal(m, b)
}
func (m *FindSmartDogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindSmartDogResponse.Marshal(b, m, deterministic)
}
func (m *FindSmartDogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindSmartDogResponse.Merge(m, src)
}
func (m *FindSmartDogResponse) XXX_Size() int {
	return xxx_messageInfo_FindSmartDogResponse.Size(m)
}
func (m *FindSmartDogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindSmartDogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindSmartDogResponse proto.InternalMessageInfo

func (m *FindSmartDogResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FindSmartDogResponse) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func init() {
	proto.RegisterType((*FindSmartDogMessage)(nil), "FindSmartDogMessage")
	proto.RegisterType((*FindSmartDogResponse)(nil), "FindSmartDogResponse")
}

func init() {
	proto.RegisterFile("api/proto/dog.proto", fileDescriptor_96e9f8fd0872a655)
}

var fileDescriptor_96e9f8fd0872a655 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2c, 0xc8, 0xd4,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0xc9, 0x4f, 0xd7, 0x03, 0xb3, 0x94, 0xb4, 0xb9, 0x84,
	0xdd, 0x32, 0xf3, 0x52, 0x82, 0x73, 0x13, 0x8b, 0x4a, 0x5c, 0xf2, 0xd3, 0x7d, 0x53, 0x8b, 0x8b,
	0x13, 0xd3, 0x53, 0x85, 0x44, 0xb8, 0x58, 0x53, 0xf2, 0xd3, 0x3d, 0x53, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0x20, 0x1c, 0x25, 0x3b, 0x2e, 0x11, 0x64, 0xc5, 0x41, 0xa9, 0xc5, 0x05, 0xf9,
	0x79, 0xc5, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x50, 0xc5, 0x60, 0x36, 0x48,
	0x2c, 0x3b, 0x33, 0x2f, 0x45, 0x82, 0x09, 0x22, 0x06, 0x62, 0x1b, 0xb9, 0x70, 0x31, 0xbb, 0xe4,
	0xa7, 0x0b, 0xd9, 0x72, 0xf1, 0x20, 0x1b, 0x23, 0x24, 0xa2, 0x87, 0xc5, 0x09, 0x52, 0xa2, 0x7a,
	0xd8, 0xec, 0x52, 0x62, 0x70, 0xe2, 0x89, 0xe2, 0x2a, 0xc8, 0x4e, 0xd7, 0x2f, 0x48, 0x02, 0x79,
	0x23, 0x89, 0x0d, 0xec, 0x0f, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x4e, 0x5c, 0x73,
	0xde, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DogClient is the client API for Dog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DogClient interface {
	FindSmartDog(ctx context.Context, in *FindSmartDogMessage, opts ...grpc.CallOption) (*FindSmartDogResponse, error)
}

type dogClient struct {
	cc grpc.ClientConnInterface
}

func NewDogClient(cc grpc.ClientConnInterface) DogClient {
	return &dogClient{cc}
}

func (c *dogClient) FindSmartDog(ctx context.Context, in *FindSmartDogMessage, opts ...grpc.CallOption) (*FindSmartDogResponse, error) {
	out := new(FindSmartDogResponse)
	err := c.cc.Invoke(ctx, "/Dog/FindSmartDog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DogServer is the server API for Dog service.
type DogServer interface {
	FindSmartDog(context.Context, *FindSmartDogMessage) (*FindSmartDogResponse, error)
}

// UnimplementedDogServer can be embedded to have forward compatible implementations.
type UnimplementedDogServer struct {
}

func (*UnimplementedDogServer) FindSmartDog(ctx context.Context, req *FindSmartDogMessage) (*FindSmartDogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSmartDog not implemented")
}

func RegisterDogServer(s *grpc.Server, srv DogServer) {
	s.RegisterService(&_Dog_serviceDesc, srv)
}

func _Dog_FindSmartDog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSmartDogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DogServer).FindSmartDog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Dog/FindSmartDog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DogServer).FindSmartDog(ctx, req.(*FindSmartDogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Dog",
	HandlerType: (*DogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindSmartDog",
			Handler:    _Dog_FindSmartDog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/dog.proto",
}
